[Migration]
Hash = "11844975519099319219"
Initial = true
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "account"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 11
Column = 9

[[Migration.Operations.Fields]]
Name = "display_name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 13
Column = 9

[[Migration.Operations.Fields]]
Name = "email"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 15
Column = 9

[[Migration.Operations.Fields]]
Name = "issuer"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 17
Column = 9

[[Migration.Operations.Fields]]
Name = "subject"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 19
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "galvynsettings"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/galvyn-contrib-settings-0.2.0/src/model.rs"
Line = 10
Column = 9

[[Migration.Operations.Fields]]
Name = "key"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/galvyn-contrib-settings-0.2.0/src/model.rs"
Line = 13
Column = 9

[[Migration.Operations.Fields]]
Name = "value"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/galvyn-contrib-settings-0.2.0/src/model.rs"
Line = 15
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "galvynsession"

[[Migration.Operations.Fields]]
Name = "id"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/galvyn-core-0.2.1/src/session.rs"
Line = 40
Column = 5

[[Migration.Operations.Fields]]
Name = "expires_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/galvyn-core-0.2.1/src/session.rs"
Line = 41
Column = 5

[[Migration.Operations.Fields]]
Name = "data"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/galvyn-core-0.2.1/src/session.rs"
Line = 42
Column = 5
